# Generated by Django 4.2 on 2025-02-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=254)),
                ('foto', models.CharField(max_length=20)),
                ('rol', models.IntegerField(choices=[(1, 'Administrador'), (2, 'Profesional'), (3, 'Secretari@'), (4, 'Cliente')], default=4)),
            ],
        ),
    ]
