# Generated by Django 4.2 on 2025-02-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254)),
                ('costo', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'ACTIVO'), ('Inactivo', 'INACTIVO')], default='Activo', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cita', models.DateTimeField(help_text='AAAA-MM-DD')),
                ('estado', models.CharField(choices=[('R', 'Reservada'), ('C', 'Cancelada'), ('A', 'Atendida')], default='R', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk1_cita_usuario_cliente', to='spa.usuario')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fk2_cita_usuario_profesional', to='spa.usuario')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spa.servicio')),
            ],
        ),
    ]
